#!/bin/bash

catkin_make

# Generate setenv.sh file on every build
ENV_FILE_NAME="./setenv.sh"
touch ${ENV_FILE_NAME}
chmod +x ${ENV_FILE_NAME}
ENV_FILE="$(readlink -f ${ENV_FILE_NAME})"

# Create the setenv.sh file everytime
THIS_FILE="$(readlink -f ./build.sh)"
echo "#!/bin/bash" > ${ENV_FILE}
echo "# DO NOT EDIT THIS FILE" >> ${ENV_FILE}
echo "# Automatically generated from:" >> ${ENV_FILE}
echo "# ${THIS_FILE}" >> ${ENV_FILE}
echo "" >> ${ENV_FILE}

PKG_ENV_FILE="$(readlink -f ./devel/setup.bash)"
source "${PKG_ENV_FILE}"
echo "source ${PKG_ENV_FILE}" >> ${ENV_FILE}
