#!/bin/bash
# DO NOT EDIT THIS FILE
# Automatically generated from:
# /home/syllogismrxs/repos/syllo-gazebo/catkin_ws/build.sh

source /home/syllogismrxs/repos/syllo-gazebo/catkin_ws/devel/setup.bash
